POST http://localhost:8080/inventoryLevel/set
Content-Type: application/json

{
  "effectiveTs": 90,
  "inventoryItem": {
    "cost": 10.00,
    "sku": "UGS-BLK-42"
  },
  "quantity": 50,
  "locationId": 0
}

###

POST http://localhost:8080/inventoryLevel/adjust
Content-Type: application/json

{
  "effectiveTs": 0,
  "inventoryItem": {
    "cost": 12.33,
    "sku": "UGS-BLK-42"
  },
  "quantity": 200,
  "locationId": 0
}

###
POST http://localhost:8080/inventoryLevel/failure
Content-Type: application/json

{
  "effectiveTs": 0,
  "inventoryItem": {
    "cost": 11.33,
    "sku": "UGS-BLK-42"
  },
  "quantity": 123,
  "locationId": 45
}